# Generated by Django 4.1.7 on 2023-07-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0003_alter_car_price_alter_car_price_usd_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmodel",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="cars_models/"),
        ),
        migrations.AlterField(
            model_name="color",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="colors/"),
        ),
        migrations.AlterField(
            model_name="interior",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="interiors/"),
        ),
        migrations.AlterField(
            model_name="seat",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="seats/"),
        ),
        migrations.AlterField(
            model_name="wheel",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="wheels/"),
        ),
    ]
