# Generated by Django 4.1.7 on 2023-07-05 21:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0004_alter_carmodel_image_alter_color_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carmodel",
            name="price_usd",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
    ]
