# Generated by Django 4.1.7 on 2023-07-11 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0006_color_price_usd_interior_price_usd_seat_price_usd_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="cars.color",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="interior",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="cars.interior",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="seat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="cars.seat",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="wheel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="cars.wheel",
            ),
        ),
    ]
